name: Deploy
on: [workflow_dispatch]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes install openvpn

      - name: Setup VPN config
        run: cat > BusMap_DEV.ovpn << EOF
          ${{ secrets.VPN_FILE }}
          EOF

      - name: Connect VPN
        run: sudo openvpn --config BusMap_DEV.ovpn --daemon

      #- name: Wait for a VPN connection
      #  timeout-minutes: 1
      #  run: until nc -z -w5 13.228.244.196 22; do sleep 2; done

      #- name: Deploy
      #  run: echo "Deploy"
